version: '3.4'
# $ cat /var/jenkins_home/secrets/initialAdminPassword
# fe6a49486a5242f58d2dcd09337fef72
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    # restart: always
    ports:
      - '8082:8080'
    volumes:
      - './jenkins_home:/var/jenkins_home'
