version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8000:8080'
    volumes:
      - './jenkins_home:/jenkins_home'
      - './maven3:/opt/maven3'